version: '3'
services:

  db:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    container_name: db_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "`1qaz@wsx"
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      LANG: C.UTF-8
    networks:
      - "mynet"

  app:
    build:
      context: .
      dockerfile: docker/apis/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: "`1qaz@wsx"
      MYSQL_DATABASE: gin_bank
    depends_on:
      - db
    networks:
      - "mynet"

networks:
  mynet:
    driver: "bridge"